Repository atlanhq/application-sdk, pull requests merged in 2025-09, with the labels that each got.

#678 Bump version to 0.1.1rc36
  CHANGELOG.md
  application_sdk/version.py
  pyproject.toml
  uv.lock
Labels: release

#682 Bump version to 0.1.1rc37
  CHANGELOG.md
  application_sdk/version.py
  pyproject.toml
  uv.lock
Labels: e2e-test, run-examples, release

#684 feat: add Hive partitioning support to ParquetOutput
  application_sdk/outputs/parquet.py
  tests/unit/outputs/test_parquet_output.py
Labels: e2e-test, run-examples

#689 Bump version to 0.1.1rc39
  CHANGELOG.md
  application_sdk/version.py
  pyproject.toml
  uv.lock
Labels: release

#691 feat: add retain_local_copy option to upload methods in ObjectStore
  application_sdk/clients/temporal.py
  application_sdk/constants.py
  application_sdk/interceptors/cleanup.py
  application_sdk/interceptors/events.py
  application_sdk/outputs/iceberg.py
  application_sdk/outputs/json.py
  application_sdk/outputs/parquet.py
  application_sdk/services/objectstore.py
  tests/unit/clients/test_temporal_client.py
  tests/unit/services/test_objectstore.py
Labels: run-examples

#696 Bump version to 0.1.1rc40
  CHANGELOG.md
  application_sdk/version.py
  pyproject.toml
  uv.lock
Labels: release

#697 feat: enhance file handling in Input classes
  application_sdk/activities/common/utils.py
  application_sdk/activities/metadata_extraction/sql.py
  application_sdk/inputs/__init__.py
  application_sdk/inputs/json.py
  application_sdk/inputs/parquet.py
  application_sdk/test_utils/hypothesis/strategies/inputs/json_input.py
  application_sdk/test_utils/hypothesis/strategies/inputs/parquet_input.py
  tests/unit/activities/common/test_utils.py
  tests/unit/activities/metadata_extraction/test_sql.py
  tests/unit/common/test_utils_file_discovery.py
  tests/unit/inputs/test_base_input.py
  tests/unit/inputs/test_json.py
  tests/unit/inputs/test_parquet.py
Labels: e2e-test, run-examples

#711 Bump version to 0.1.1rc42
  CHANGELOG.md
  application_sdk/version.py
  pyproject.toml
  uv.lock
Labels: release

#702 fix: file not found exception across cloud providers, suppress logs in case of upsert
  application_sdk/services/objectstore.py
  application_sdk/services/statestore.py
  tests/unit/services/test_objectstore.py
  tests/unit/services/test_statestore.py
Labels: e2e-test, run-examples

#700 fix: memory management issues with readers and writers
  application_sdk/activities/metadata_extraction/sql.py
  application_sdk/activities/query_extraction/sql.py
  application_sdk/inputs/parquet.py
  application_sdk/inputs/sql_query.py
  application_sdk/interceptors/cleanup.py
  application_sdk/outputs/__init__.py
  application_sdk/outputs/json.py
  application_sdk/outputs/parquet.py
  application_sdk/transformers/query/__init__.py
  application_sdk/workflows/metadata_extraction/sql.py
  tests/unit/activities/metadata_extraction/test_sql.py
  tests/unit/common/test_credential_utils.py
  tests/unit/inputs/test_base_input.py
  tests/unit/inputs/test_parquet.py
  tests/unit/outputs/test_json_output.py
  tests/unit/outputs/test_output.py
  tests/unit/outputs/test_parquet_output.py
  tests/unit/workflows/metadata_extraction/test_sql_workflow.py
Labels: e2e-test, run-examples

#698 feat: add MCP (Model Context Protocol) integration to application-sdk
  application_sdk/application/__init__.py
  application_sdk/constants.py
  application_sdk/decorators/mcp_tool.py
  application_sdk/server/mcp/__init__.py
  application_sdk/server/mcp/models.py
  application_sdk/server/mcp/server.py
  docs/docs/concepts/mcp.md
  pyproject.toml
  tests/unit/decorators/__init__.py
  tests/unit/decorators/test_mcp_tool.py
  tests/unit/server/mcp/__init__.py
  tests/unit/server/mcp/test_mcp_server.py
  uv.lock
Labels: e2e-test, run-examples

#727 Bump version to 0.1.1rc46
  CHANGELOG.md
  application_sdk/version.py
  pyproject.toml
  uv.lock
Labels: release

#734 Bump version to 0.1.1rc47
  CHANGELOG.md
  application_sdk/version.py
  pyproject.toml
  uv.lock
Labels: release

#737 Bump version to 0.1.1rc48
  CHANGELOG.md
  application_sdk/version.py
  pyproject.toml
  uv.lock
Labels: release

#735 fix: Make Changelog script use GitHub usernames instead of Git Author Names
  .github/scripts/update_changelog.py
Labels: e2e-test, run-examples

#729 feat: bump dapr version to 1.16.0
  .cursor/rules/setup.mdc
  .github/actions/e2e-examples/action.yaml
  .github/workflows/scale-tests.yaml
  docs/docs/setup/LINUX.md
  docs/docs/setup/MAC.md
  docs/docs/setup/WINDOWS.md
  pyproject.toml
  uv.lock
Labels: e2e-test, run-examples

#743 Bump version to 0.1.1rc50
  CHANGELOG.md
  application_sdk/version.py
  pyproject.toml
  uv.lock
Labels: release
