Repository atlanhq/application-sdk, pull requests merged in 2025-05, with the labels that each got.

#454 feat: add passthrough_modules parameter to setup_workflow method
  .github/actions/docgen/action.yaml
  .github/workflow-templates/checks.yaml
  application_sdk/application/__init__.py
  application_sdk/application/metadata_extraction/sql.py
  application_sdk/worker.py
  poetry.lock
Labels: run-examples

#455 feat: develop to main
  .cursor/rules/setup.mdc
  .github/actions/docgen/action.yaml
  .github/actions/e2e-examples/action.yaml
  .github/actions/setup-deps/action.yaml
  .github/actions/unit-tests/action.yaml
  .github/pull_request_template.md
  .github/workflow-templates/checks.yaml
  .github/workflows/codeql.yaml
  .github/workflows/pull_request.yaml
  .github/workflows/push.yaml
  .github/workflows/release.yaml
  .github/workflows/scale-tests.yaml
  application_sdk/application/__init__.py
  application_sdk/application/metadata_extraction/sql.py
  application_sdk/test_utils/hypothesis/strategies/application/fastapi/__init__.py
  application_sdk/test_utils/hypothesis/strategies/server/__init__.py
  application_sdk/test_utils/hypothesis/strategies/server/fastapi/__init__.py
  application_sdk/worker.py
  docs/docs/setup/LINUX.md
  docs/docs/setup/MAC.md
  docs/docs/setup/WINDOWS.md
  poetry.lock
  tests/unit/server/__init__.py
  tests/unit/server/fastapi/routers/__init__.py
  tests/unit/server/fastapi/routers/server.py
  tests/unit/server/fastapi/test__init__.py
Labels: run-examples

#468 docs: fix pipeline
  .github/actions/unit-tests/action.yaml
  .github/workflows/pull_request.yaml
  .github/workflows/push.yaml
Labels: documentation, bugfix

#478 Bump version to 0.1.1rc1
  CHANGELOG.md
  application_sdk/version.py
  poetry.lock
  pyproject.toml
Labels: release

#467 fix: Fix date datatype in transformed output
  application_sdk/outputs/json.py
  application_sdk/transformers/atlas/__init__.py
Labels: run-examples, bugfix

#484 chore: update docs after package publish
  .github/workflows/tag-and-publish.yaml
  Makefile
  NOTICE
  README.md
  application_sdk/constants.py
Labels: documentation, ignore

#509 Bump version to 0.1.1rc2
  CHANGELOG.md
  application_sdk/version.py
  pyproject.toml
Labels: e2e-test, run-examples, release

#511 Fix: Diff for custom attributes in table asset
  application_sdk/transformers/query/templates/table.yaml
  tests/unit/transformers/query/resources/transformed/table.json
Labels: e2e-test, run-examples

#520 fix: transformer with custom_attributes and dependency bump
  .github/workflows/tag-and-publish.yaml
  application_sdk/transformers/query/templates/table.yaml
  poetry.lock
  tests/unit/transformers/query/resources/transformed/table.json
Labels: e2e-test, run-examples

#521 Bump version to 0.1.1rc3
  CHANGELOG.md
  application_sdk/version.py
  poetry.lock
  pyproject.toml
Labels: e2e-test, run-examples, release

#485 feat: migrate to uv, goodbye poetry
  .cursor/rules/guidelines.mdc
  .cursor/rules/logging.mdc
  .cursor/rules/setup.mdc
  .cursor/rules/standards.mdc
  .cursor/rules/testing.mdc
  .github/actions/docgen/action.yaml
  .github/actions/e2e-examples/action.yaml
  .github/actions/setup-deps/action.yaml
  .github/actions/unit-tests/action.yaml
  .github/scripts/pre_release.py
  .github/scripts/release.py
  .github/workflow-templates/checks.yaml
  .github/workflows/pre-release.yaml
  .github/workflows/pull_request.yaml
  .github/workflows/push.yaml
  .github/workflows/release.yaml.disabled
  .github/workflows/scale-tests.yaml
  .github/workflows/tag-and-publish.yaml
  .gitignore
  Makefile
  README.md
  application_sdk/activities/metadata_extraction/sql.py
  application_sdk/constants.py
  application_sdk/handlers/sql.py
  application_sdk/test_utils/scale_data_generator/README.md
  docs/docs/configuration.md
  docs/docs/guides/atlantis.md
  docs/docs/guides/test-framework.md
  docs/docs/index.md
  docs/docs/setup/LINUX.md
  docs/docs/setup/MAC.md
  docs/docs/setup/WINDOWS.md
  examples/README.md
  poetry.lock
  pyproject.toml
  uv.lock
Labels: enhancement, dependencies, run-examples, breaking

#522 feat: migrate to uv, goodbye poetry
  .cursor/rules/guidelines.mdc
  .cursor/rules/logging.mdc
  .cursor/rules/setup.mdc
  .cursor/rules/standards.mdc
  .cursor/rules/testing.mdc
  .github/actions/docgen/action.yaml
  .github/actions/e2e-examples/action.yaml
  .github/actions/setup-deps/action.yaml
  .github/actions/unit-tests/action.yaml
  .github/scripts/pre_release.py
  .github/scripts/release.py
  .github/workflow-templates/checks.yaml
  .github/workflows/pre-release.yaml
  .github/workflows/pull_request.yaml
  .github/workflows/push.yaml
  .github/workflows/release.yaml.disabled
  .github/workflows/scale-tests.yaml
  .github/workflows/tag-and-publish.yaml
  .gitignore
  Makefile
  README.md
  application_sdk/activities/metadata_extraction/sql.py
  application_sdk/constants.py
  application_sdk/handlers/sql.py
  application_sdk/test_utils/scale_data_generator/README.md
  docs/docs/configuration.md
  docs/docs/guides/atlantis.md
  docs/docs/guides/test-framework.md
  docs/docs/index.md
  docs/docs/setup/LINUX.md
  docs/docs/setup/MAC.md
  docs/docs/setup/WINDOWS.md
  examples/README.md
  poetry.lock
  pyproject.toml
  uv.lock
Labels: enhancement, run-examples

#523 Bump version to 0.1.1rc4
  CHANGELOG.md
  application_sdk/version.py
  pyproject.toml
  uv.lock
Labels: release

#524 fix: uv optional dependencies and groups
  .github/actions/e2e-examples/action.yaml
  .github/actions/setup-deps/action.yaml
  .github/workflow-templates/checks.yaml
  .github/workflows/pre-release.yaml
  .github/workflows/release.yaml.disabled
  .github/workflows/scale-tests.yaml
  .github/workflows/tag-and-publish.yaml
  application_sdk/test_utils/scale_data_generator/README.md
  docs/docs/setup/LINUX.md
  docs/docs/setup/MAC.md
  docs/docs/setup/WINDOWS.md
  pyproject.toml
  uv.lock
Labels: run-examples

#473 feat: add logging adapter with objectstore sink
  .github/actions/unit-tests/action.yaml
  application_sdk/common/logger_adaptors.py
  application_sdk/common/observability.py
  application_sdk/constants.py
  application_sdk/server/fastapi/__init__.py
  docs/docs/concepts/common.md
  docs/docs/configuration.md
  tests/unit/common/test_logger_adapter.py
Labels: enhancement, run-examples

#492 feat: add metric adapter with objectstore sink
  application_sdk/common/logger_adaptors.py
  application_sdk/common/metrics_adaptor.py
  application_sdk/common/observability.py
  application_sdk/constants.py
  application_sdk/outputs/objectstore.py
  application_sdk/server/fastapi/__init__.py
  docs/docs/concepts/common.md
  docs/docs/configuration.md
  tests/unit/common/test_logger_adapter.py
  tests/unit/common/test_metrics_adapter.py
Labels: e2e-test

#510 feat : Add minimal set of metrics for all apps
  application_sdk/outputs/iceberg.py
  application_sdk/outputs/json.py
  application_sdk/outputs/parquet.py
  application_sdk/workflows/metadata_extraction/sql.py
Labels: e2e-test

#512 feat : Add hierarchal logging structure + failsafe log flush mechanism
  application_sdk/common/logger_adaptors.py
  application_sdk/common/metrics_adaptor.py
  application_sdk/common/observability.py
  application_sdk/constants.py
  docs/docs/concepts/common.md
Labels: e2e-test

#513 feat : Add traces adaptor
  application_sdk/common/logger_adaptors.py
  application_sdk/common/traces_adaptor.py
  application_sdk/constants.py
  docs/docs/configuration.md
  tests/unit/common/test_traces_adaptor.py
Labels: e2e-test

#532 Fix: JsonOutput type checking while writing dataframe
  application_sdk/outputs/json.py
Labels: run-examples

#531 Fix: Query transformer diff fixes
  application_sdk/transformers/query/templates/column.yaml
  application_sdk/transformers/query/templates/table.yaml
  tests/unit/transformers/query/resources/raw/column.json
  tests/unit/transformers/query/resources/raw/table.json
  tests/unit/transformers/query/resources/transformed/column.json
  tests/unit/transformers/query/resources/transformed/table.json
Labels: e2e-test, run-examples

#537 fix: pandas import in SqlQueryInput class
  application_sdk/inputs/sql_query.py
Labels: e2e-test, run-examples

#493 Enhance workflow activity collection and allow custom output prefix
  application_sdk/application/metadata_extraction/sql.py
  application_sdk/clients/temporal.py
Labels: run-examples

#539 fix : APP-6790
  application_sdk/common/logger_adaptors.py
  tests/unit/common/test_logger_adapter.py
Labels: e2e-test

#540 fix : APP-6789
  pyproject.toml
Labels: e2e-test

#551 fix: Use pandas instead of daft for executing extraction queries
  application_sdk/activities/metadata_extraction/sql.py
  application_sdk/common/dataframe_utils.py
  application_sdk/handlers/sql.py
  application_sdk/inputs/parquet.py
  application_sdk/inputs/sql_query.py
  application_sdk/outputs/__init__.py
  application_sdk/outputs/json.py
  application_sdk/outputs/parquet.py
  pyproject.toml
  tests/unit/clients/test_async_sql_client.py
  tests/unit/clients/test_sql_client.py
  tests/unit/handlers/sql/test_auth.py
  tests/unit/handlers/sql/test_check_schemas_and_databases.py
  tests/unit/handlers/sql/test_prepare_metadata.py
  tests/unit/handlers/sql/test_tables_check.py
  tests/unit/outputs/test_output.py
  uv.lock
Labels: run-examples, atlan-postgres-app:use_pandas_for_querying

#550 feat: APP-6309 Standardised error codes
  application_sdk/activities/__init__.py
  application_sdk/clients/sql.py
  application_sdk/common/error_codes.py
  application_sdk/common/utils.py
  application_sdk/inputs/json.py
  application_sdk/inputs/statestore.py
  application_sdk/observability/logger_adaptor.py
  application_sdk/observability/metrics_adaptor.py
  application_sdk/outputs/iceberg.py
  application_sdk/outputs/json.py
  application_sdk/outputs/parquet.py
  application_sdk/server/fastapi/__init__.py
  application_sdk/workflows/metadata_extraction/sql.py
  docs/docs/concepts/common.md
  tests/unit/clients/test_sql_client.py
  tests/unit/common/test_metrics_adapter.py
  tests/unit/common/test_utils.py
  tests/unit/outputs/test_statestore.py
Labels: e2e-test, run-examples

#545 Bump version to 0.1.1rc6
  CHANGELOG.md
  application_sdk/version.py
  pyproject.toml
  uv.lock
Labels: release, do not merge

#557 Bump version to 0.1.1rc7
  CHANGELOG.md
  application_sdk/version.py
  pyproject.toml
  uv.lock
Labels: release, do not merge

#561 feat: Add SQLAlchemy url support
  application_sdk/clients/sql.py
  tests/unit/clients/test_sql_client.py
Labels: e2e-test, run-examples

#564 Bump version to 0.1.1rc8
  CHANGELOG.md
  application_sdk/version.py
  pyproject.toml
  uv.lock
Labels: release

#566 Bump version to 0.1.1rc9
  CHANGELOG.md
  application_sdk/version.py
  pyproject.toml
  uv.lock
Labels: release

#559 fix : Created an observability decorator
  application_sdk/application/metadata_extraction/sql.py
  application_sdk/observability/decorators/observability_decorator.py
  application_sdk/observability/traces_adaptor.py
  docs/docs/concepts/observability.mdc
Labels: e2e-test, run-examples

#567 Bump version to 0.1.1rc10
  CHANGELOG.md
  application_sdk/version.py
  pyproject.toml
  uv.lock
Labels: release
