Repository atlanhq/application-sdk, pull requests merged in 2025-06, with the labels that each got.

#568 Fix: Changed application -> server, custom servers in constructor should work
  application_sdk/application/__init__.py
  application_sdk/application/metadata_extraction/sql.py
Labels: run-examples

#571 Bump version to 0.1.1rc11
  CHANGELOG.md
  application_sdk/version.py
  pyproject.toml
  uv.lock
Labels: release

#577 Bump version to 0.1.1rc14
  CHANGELOG.md
  application_sdk/version.py
  pyproject.toml
  uv.lock
Labels: release

#560 APP-6781 event based workflows
  application_sdk/application/__init__.py
  application_sdk/clients/temporal.py
  application_sdk/constants.py
  application_sdk/outputs/eventstore.py
  application_sdk/server/fastapi/__init__.py
  application_sdk/server/fastapi/models.py
  application_sdk/test_utils/hypothesis/strategies/server/fastapi/__init__.py
  components/subscription.yaml
  docs/docs/concepts/server.md
  examples/application_subscriber.py
  pyproject.toml
  tests/unit/server/fastapi/test__init__.py
Labels: run-examples

#586 Bump version to 0.1.1rc15
  CHANGELOG.md
  application_sdk/version.py
  pyproject.toml
  uv.lock
Labels: release

#528 feat: [SQL Query transformer] Improve attribute definitions in yaml templates
  .github/actions/unit-tests/action.yaml
  application_sdk/transformers/common/utils.py
  application_sdk/transformers/query/__init__.py
  application_sdk/transformers/query/templates/column.yaml
  application_sdk/transformers/query/templates/database.yaml
  application_sdk/transformers/query/templates/extras-procedure.yaml
  application_sdk/transformers/query/templates/function.yaml
  application_sdk/transformers/query/templates/schema.yaml
  application_sdk/transformers/query/templates/table.yaml
  application_sdk/transformers/query/templates/tag_attachment.yaml
  examples/sql_query_templates/database.yaml
  tests/unit/transformers/query/test_sql_transformer.py
Labels: e2e-test, run-examples

#587 fix: Fetch queries activity in SQLQueryExtractionActivities
  application_sdk/activities/query_extraction/sql.py
Labels: run-examples

#592 Bump version to 0.1.1rc17
  CHANGELOG.md
  application_sdk/version.py
  pyproject.toml
  uv.lock
Labels: release

#593 Bump version to 0.1.1rc18
  CHANGELOG.md
  application_sdk/version.py
  pyproject.toml
  uv.lock
Labels: release

#598 fix: defaults for fetch_metadata endpoint, simplify handler
  application_sdk/handlers/sql.py
  application_sdk/server/fastapi/__init__.py
  examples/application_fastapi.py
Labels: e2e-test, run-examples
