Repository atlanhq/application-sdk, pull requests merged in 2025-08, with the labels that each got.

#623 feat: Add utility function to fetch include/exclude databases from include-exclude regex
  application_sdk/common/utils.py
  tests/unit/common/test_utils.py
Labels: e2e-test, run-examples

#627 Bump version to 0.1.1rc24
  CHANGELOG.md
  application_sdk/version.py
  pyproject.toml
  uv.lock
Labels: release

#634 feat: implement OAuth2 authentication and data transfer for applications
  .env.example
  application_sdk/activities/metadata_extraction/sql.py
  application_sdk/activities/query_extraction/sql.py
  application_sdk/clients/atlan_auth.py
  application_sdk/clients/sql.py
  application_sdk/clients/temporal.py
  application_sdk/common/credential_utils.py
  application_sdk/common/error_codes.py
  application_sdk/constants.py
  application_sdk/inputs/objectstore.py
  application_sdk/inputs/secretstore.py
  application_sdk/inputs/statestore.py
  application_sdk/observability/observability.py
  application_sdk/outputs/atlan_storage.py
  application_sdk/outputs/objectstore.py
  application_sdk/outputs/statestore.py
  application_sdk/workflows/metadata_extraction/sql.py
  components/atlan-storage.yaml
  components/deployment-secrets.yaml
  docs/docs/concepts/atlanupload.md
  docs/docs/concepts/inputs.md
  docs/docs/concepts/temporal_auth.md
  pyproject.toml
  tests/conftest.py
  tests/unit/clients/test_atlan_auth.py
  tests/unit/clients/test_atlanauth.py
  tests/unit/clients/test_sql_client.py
  tests/unit/clients/test_temporal_client.py
  tests/unit/common/test_credential_utils.py
  tests/unit/outputs/test_atlanstorage.py
  tests/unit/outputs/test_objectstore.py
  tests/unit/outputs/test_statestore.py
  tests/unit/workflows/metadata_extraction/test_sql.py
  uv.lock
Labels: e2e-test, run-examples

#637 Bump version to 0.1.1rc26
  CHANGELOG.md
  application_sdk/version.py
  pyproject.toml
  uv.lock
Labels: release

#639 fix: replace getdaft with daft
  NOTICE
  pyproject.toml
  uv.lock
Labels: e2e-test, run-examples

#642 feat: add pyatlan Client to Application SDK
  application_sdk/clients/atlan_client.py
  application_sdk/constants.py
  pyproject.toml
  tests/unit/clients/test_atlan_client.py
  uv.lock
Labels: e2e-test, run-examples

#645 Bump version to 0.1.1rc28
  CHANGELOG.md
  application_sdk/version.py
  pyproject.toml
  uv.lock
Labels: release

#647 fix: error logs for eventstore, objectstore and metrics
  application_sdk/common/dapr_utils.py
  application_sdk/handlers/sql.py
  application_sdk/inputs/statestore.py
  application_sdk/outputs/eventstore.py
  application_sdk/outputs/statestore.py
  application_sdk/server/fastapi/__init__.py
  docs/docs/concepts/outputs.md
Labels: e2e-test, run-examples

#648 Bump version to 0.1.1rc29
  CHANGELOG.md
  application_sdk/version.py
  pyproject.toml
  uv.lock
Labels: release

#651 fix: error logs related to deployment secrets
  application_sdk/inputs/secretstore.py
Labels: e2e-test, run-examples

#635 feat: support for app registration via events
  application_sdk/application/__init__.py
  application_sdk/clients/temporal.py
  application_sdk/constants.py
  application_sdk/events/__init__.py
  application_sdk/events/models.py
  application_sdk/observability/observability.py
  application_sdk/outputs/eventstore.py
  application_sdk/server/fastapi/__init__.py
  application_sdk/server/fastapi/models.py
  application_sdk/test_utils/hypothesis/strategies/server/fastapi/__init__.py
  application_sdk/worker.py
  components/eventstore.yaml
  tests/conftest.py
  tests/unit/application/metadata_extraction/test_sql.py
  tests/unit/application/test_application.py
  tests/unit/clients/test_temporal_client.py
  tests/unit/outputs/test_eventstore.py
  tests/unit/test_worker.py
Labels: e2e-test, run-examples

#659 fix: Parquet file output path with None file names
  application_sdk/inputs/parquet.py
  application_sdk/test_utils/hypothesis/strategies/inputs/parquet_input.py
  tests/unit/inputs/test_parquet.py
Labels: atlan-postgres-app:main, run-examples

#664 fix: Update APP_HOST env variable default value
  application_sdk/constants.py
Labels: atlan-postgres-app:main, run-examples

#668 Bump version to 0.1.1rc33
  CHANGELOG.md
  application_sdk/version.py
  pyproject.toml
  uv.lock
Labels: release

#672 Bump version to 0.1.1rc34
  CHANGELOG.md
  application_sdk/version.py
  pyproject.toml
  uv.lock
Labels: release
